CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY,  -- Identificador ?nico autoincremental
    nombre VARCHAR2(50) NOT NULL,                        -- Nombre del usuario
    contrasena VARCHAR2(100) NOT NULL,                   -- Contrase?a del usuario
    PRIMARY KEY (id_usuario)
);  

INSERT INTO usuario (nombre, contrasena)
VALUES ('Rodolfo', 'pase1234');

CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,  
    nombre VARCHAR2(50) NOT NULL,  
    apellido VARCHAR2(50) NOT NULL,
    ciudad VARCHAR2(50),
    direccion VARCHAR2(100),
    correo VARCHAR2(100),
    telefono VARCHAR2(20),
    nit VARCHAR2(20),  
    fecha_registro DATE,  
    PRIMARY KEY (id_cliente)  
);

CREATE TABLE habitaciones (
    ID_habitacion NUMBER GENERATED BY DEFAULT AS IDENTITY, -- Identificador ?nico autoincremental
    numero_habitacion VARCHAR2(10) NOT NULL,              -- N?mero de la habitaci?n
    tipo_habitacion VARCHAR2(50),                         -- Tipo de la habitaci?n
    descripcion VARCHAR2(255),                            -- Descripci?n de la habitaci?n
    precio_noche NUMBER(10, 2),                           -- Precio por noche (decimales permitidos)
    capacidad NUMBER(5),                                  -- Capacidad de personas en la habitaci?n
    estado_habitacion NUMBER (2),                       -- Estado de la habitaci?n (e.g. disponible, ocupado)
    PRIMARY KEY (ID_habitacion)
);

CREATE TABLE reservaciones (
    ID_reservacion NUMBER GENERATED BY DEFAULT AS IDENTITY,  -- Identificador ?nico autoincremental para la reservaci?n
    id_cliente NUMBER NOT NULL,                              -- ID del cliente (relacionado con la tabla cliente)
    ID_habitacion NUMBER NOT NULL,                           -- ID de la habitaci?n (relacionado con la tabla habitaciones)
    fecha_reserva DATE,                                      -- Fecha en la que se hizo la reservaci?n
    fecha_entrada DATE,                                      -- Fecha de entrada
    fecha_salida DATE,                                       -- Fecha de salida
    numero_huespedes NUMBER(3),                              -- N?mero de hu?spedes
    estado_reserva NUMBER (2),                                      -- Estado de la reserva
    PRIMARY KEY (ID_reservacion),
    FOREIGN KEY (ID_cliente) REFERENCES cliente(ID_cliente),   -- Clave for?nea relacionada con la tabla cliente
    FOREIGN KEY (ID_habitacion) REFERENCES habitaciones(ID_habitacion)  -- Clave for?nea relacionada con la tabla habitaciones
);

CREATE TABLE facturas (
    ID_factura NUMBER GENERATED BY DEFAULT AS IDENTITY,  -- Identificador ?nico autoincremental para la factura
    ID_reservacion NUMBER NOT NULL,                      -- ID de la reservaci?n (relacionado con la tabla reservaciones)
    ID_cliente NUMBER NOT NULL,                          -- ID del cliente (relacionado con la tabla cliente)
    monto_total NUMBER(10, 2) NOT NULL,                  -- Monto total de la factura
    fecha_emision DATE DEFAULT SYSDATE,                  -- Fecha de emisi?n de la factura con valor por defecto la fecha actual
    detalles_factura VARCHAR2(500),                      -- Detalles adicionales de la factura
    PRIMARY KEY (ID_factura),
    FOREIGN KEY (ID_reservacion) REFERENCES reservaciones(ID_reservacion),  -- Relaci?n con la tabla reservaciones
    FOREIGN KEY (ID_cliente) REFERENCES cliente(ID_cliente)                -- Relaci?n con la tabla cliente
);