-- USER SQL
CREATE USER "PROYECTOPROGRA" IDENTIFIED BY "proyectoprogra"  ;

-- QUOTAS

-- ROLES
GRANT "DBA" TO "PROYECTOPROGRA" ;
GRANT "CONNECT" TO "PROYECTOPROGRA" ;
GRANT "RESOURCE" TO "PROYECTOPROGRA" ;

-- SYSTEM PRIVILEGES

